import type { PersonModel } from "../models/PersonModel";

export const teamMembers: { [id: string]: PersonModel } = {
  sia: {
    firstName: "Sia",
    lastName: "van Keijsteren",
    organisation: "Universiteit Utrecht",
    roles: ["Landelijke Projectmanager"],
    email: "co-teach@uu.nl",
    personalPage: "https://www.uu.nl/medewerkers/TJMvanKeijsteren",
  },
  rachel: {
    firstName: "Rachel",
    lastName: "Baan",
    organisation: "Universiteit Utrecht",
    roles: ["Vakdidacticus Utrecht"],
    personalPage: "https://www.linkedin.com/in/rachelbaan/",
  },
  ingrid: {
    firstName: "Ingrid",
    lastName: "Breymann",
    organisation: "Universiteit Twente",
    roles: ["Vakdidacticus Twente"],
    personalPage: "https://personen.utwente.nl/l.e.i.breymann",
  },
  yuen: {
    firstName: "Yuen",
    lastName: "Ng",
    organisation: "Vrije Universiteit Amsterdam",
    roles: ["Vakdidacticus Amsterdam"],
    personalPage: "https://www.linkedin.com/in/yuenkeongng/",
  },
  ilona: {
    firstName: "Ilona",
    lastName: "Friso-van den Bos",
    organisation: "Universiteit Twente",
    roles: ["Relatiebeheer"],
    email: "i.friso-vandenbos@utwente.nl",
    personalPage: "https://www.linkedin.com/in/ilonafriso/",
  },
  alie: {
    firstName: "Alie",
    lastName: "Blume",
    organisation: "Universiteit Twente",
    roles: ["Evaluatie en effectmeting"],
  },
  koos: {
    firstName: "Koos",
    lastName: "Bax",
    organisation: "Universiteit Utrecht",
    roles: ["Communicatiemedewerker"],
    personalPage: "https://www.linkedin.com/in/koos-bax-bb9595197/",
  },
  rhea: {
    firstName: "Rhea",
    lastName: "van der Dong",
    organisation: "Universiteiten van Nederland",
    roles: ["Lid namens UNL"],
    personalPage:
      "https://www.universiteitenvannederland.nl/nl_NL/vsnu-team-detail.html/medewerker/236",
  },
  fleur: {
    firstName: "Fleur",
    lastName: "Veringa",
    organisation: "VO-raad",
    roles: ["Lid namens VO-raad"],
    personalPage: "https://nl.linkedin.com/in/fleur-veringa-8abb5a3b",
  },
  jelmer: {
    firstName: "Jelmer",
    lastName: "Schreuder",
    organisation: "NLdigital",
    roles: ["Lid namens NLdigital"],
    personalPage: "https://www.linkedin.com/in/jschreuder/",
  },
  jos: {
    firstName: "Jos",
    lastName: "Tolboom",
    organisation: "SLO",
    roles: ["Lid namens SLO"],
    personalPage: "https://www.slo.nl/zoeken/@1770/jos-tolboom/",
  },
  aad: {
    firstName: "Aad",
    lastName: "van der Drift",
    organisation: "i&i",
    roles: ["Lid namens i&i"],
    personalPage: "https://www.linkedin.com/in/avddrift/",
  },
  pieter: {
    firstName: "Pieter",
    lastName: "Duisenberg",
    organisation: "Universiteiten van Nederland",
    roles: ["Voorzitter"],
    personalPage:
      "https://www.universiteitenvannederland.nl/nl_NL/vsnu-team-detail.html/medewerker/185",
  },
  michiel: {
    firstName: "Michiel",
    lastName: "van Vlimmeren",
    organisation: "NLdigital",
    roles: ["Stuurgroeplid"],
    personalPage:
      "https://www.salesforce.com/nl/blog/authors/Michiel-van-Vlimmeren",
  },
  gerard: {
    firstName: "Gerard",
    lastName: "Barkema",
    organisation: "Universiteit Utrecht",
    roles: ["Stuurgroeplid"],
    personalPage: "https://www.uu.nl/medewerkers/GTBarkema",
  },
  diana: {
    firstName: "Diana",
    lastName: "Warmerdam",
    organisation: "Universiteit Utrecht",
    roles: ["Administratief medewerker"],
    personalPage: "https://www.linkedin.com/in/diana-warmerdam-7565b619b/",
  },
  andor: {
    firstName: "Andor",
    lastName: "Michels",
    organisation: "Universiteit Utrecht",
    roles: ["Audiovisuele vormgever"],
    personalPage: "https://nl.linkedin.com/in/andor-michels-059810123",
  },
  paulina: {
    firstName: "Paulina",
    lastName: "Moerland",
    organisation: "Universiteit Utrecht",
    roles: ["Vaksteunpunt Utrecht"],
    personalPage: "https://nl.linkedin.com/in/paulina-moerland-2706b317a",
  },
  thirza: {
    firstName: "Thirza",
    lastName: "Hiwat",
    organisation: "Universiteit Utrecht",
    roles: ["Vaksteunpunt Utrecht"],
    personalPage: "https://nl.linkedin.com/in/thirzahiwat",
  },
  denise: {
    firstName: "Denise",
    lastName: "den Hartog",
    organisation: "Universiteit Twente",
    roles: ["Vaksteunpunt Twente"],
    personalPage: "https://www.linkedin.com/in/denise-den-hartog-0057621a8/",
  },
  karlijn: {
    firstName: "Karlijn",
    lastName: "Kole",
    organisation: "Universiteit Twente",
    roles: ["Vaksteunpunt Twente"],
    personalPage: "https://www.linkedin.com/in/karlijn-kole-08a5341a9/",
  },
  ingriddebonth: {
    firstName: "Ingrid",
    lastName: "de Bonth",
    organisation: "VO-raad",
    roles: ["Stuurgroeplid"],
    personalPage: "https://www.linkedin.com/in/ingrid-de-bonth-7b05304",
  },
  heather: {
    firstName: "Heather",
    lastName: "Huijting",
    organisation: "Universiteit Utrecht",
    roles: ["Landelijk Secretaresse"],
    personalPage: "https://www.linkedin.com/in/heather-huijting-2aa201166/ ",
  },
};
